/// Flutter icons CertifyIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CertifyIcon
///      fonts:
///       - asset: fonts/CertifyIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CertifyIcon {
  CertifyIcon._();

  static const _kFontFam = 'CertifyIcon';
  static const String _kFontPkg = null;

  static const IconData perm_identity = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData false_mostly = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData false_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mix = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData outdated = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person1 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birthdate = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person2 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_withbg = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_signin = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trend = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_name = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData validation_success = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData true_mostly = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData true_icon = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unproven = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData app_icon = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_not_filled = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_not_filled = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trend_filled = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forowrd = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData country = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email_signin = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gender = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invisible_pass = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData legend = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData miscaptioned = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scam = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visible_pass = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password_signin_1 = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unfilled_home = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_validation = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filled_person = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filled_chart_bar = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filled_add = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filled_star = IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
