name: certifyapp
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.10.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1


  # http client
  #connectivity: ^2.0.2

  # State Management
  provider: ^4.3.1

  #Dependency Injection
  get_it: ^4.0.2

  # Native
  flutter_device_type: ^0.2.0
  url_launcher: ^5.5.0
  shared_preferences: ^0.5.8
  flutter_flexible_toast: ^0.1.4

  # Progress bar
  progress_hud_v2: ^2.0.0
  percent_indicator: ^2.1.5

  # Icons
  feather_icons_flutter: any
  eva_icons_flutter: any
  font_awesome_flutter: any
  cupertino_icons: ^0.1.3
  flutter_feather_icons: ^1.0.3



  # UI Reqs
  hexcolor: ^1.0.1

  # charts
  charts_flutter: ^0.9.0

  # Flutter Link Preview
  flutter_link_preview: ^1.5.6
  cached_network_image: ^2.4.1

  # Web View Flutter
  webview_flutter: ^1.0.7
  flutter_webview_plugin: ^0.3.11
  flutter_inappwebview: 4.0.0+4




  # Progress Indicators
  progress_indicators: ^0.1.5

  #sharing process
  receive_sharing_intent: ^1.4.3
  share: ^0.6.5+4

  #carousel_slider
  carousel_slider: ^3.0.0

  # Encrypt
  encrypt: ^4.1.0



  # Firebase
  firebase_core: 0.4.4
  firebase_analytics: 4.0.2
  firebase_auth: 0.15.3
  firebase_storage: 3.1.3
  firebase_messaging: 6.0.13
  cloud_firestore: 0.13.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any


flutter:
  uses-material-design: true

  # assets:
  assets:
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Regular.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf
          weight: 700
    - family: Helvetica_Neue_LTStd
      fonts:
        - asset: assets/fonts/Helvetica_Neue_LTStd/HelveticaNeueLTStd-Bd.otf
        - asset: assets/fonts/Helvetica_Neue_LTStd/HelveticaNeueLTStd-It.otf
        - asset: assets/fonts/Helvetica_Neue_LTStd/HelveticaNeueLTStd-Lt.otf
        - asset: assets/fonts/Helvetica_Neue_LTStd/HelveticaNeueLTStd-Md.otf
        - asset: assets/fonts/Helvetica_Neue_LTStd/HelveticaNeueLTStd-Roman.otf
    - family: MuseoSans
      fonts:
        - asset: assets/fonts/Museo/MuseoSans.otf

    - family: CertifyIcon
      fonts:
        - asset: lib/app-icons/fonts/CertifyIcon.ttf
